[build]
	command = "npm run build"
	publish = "build"

[functions]
	directory = "netlify/functions"
	node_bundler = "esbuild"

[[redirects]]
	from = "/api/holidays"
	to = "/404"
	status = 404
	force = true

[[redirects]]
	from = "/api/weather"
	to = "/404"
	status = 404
	force = true

[[redirects]]
	from = "/*"
	to = "/index.html"
	status = 200
